### ISSUE TITLE
Request: Update the Japanese website for a fix

### ISSUE THREAD

**Issue by hitomik723** [appliedepi/epiRhandbook_jp#104]
Hi @nsbatra,

We found that one of our translator's profile link is wrong on our current website, so we replaced it with a correct link and placed fully-rendered htmls into the html_outputs folder of the master branch of the epirhandbook_jp repo.

Could you update the Japanese website? Thank you and my apologies for the inconvenience.

Cc. @ysaito8015 @Seito-N

**Comment by ysaito8015** [comment]
related PR https://github.com/appliedepi/epiRhandbook_jp/pull/103

**Comment by nsbatra** [comment]
Hi Hitomi, thanks for tagging me. I'll try to do this week.

**Comment by hitomik723** [comment]
Hi @nsbatra Sorry for interrupting you when you're busy - could you update our Japanese R Epi handbook website at your earliest convenience? It looks like one of our translators' profile is still linked to an wrong web page. Thank you always for your support!

Cc. @ysaito8015 @Seito-N

**Comment by nsbatra** [comment]
Hi @hitomik723 I have updated the site. Can you confirm that the fix has been registered? Thanks

**Comment by hitomik723** [comment]
@nsbatra I confirmed that the fix is now reflected. Thank you so much, Neale!
