### ISSUE TITLE
Update Japanese Website

### ISSUE THREAD

**Issue by ysaito8015** [appliedepi/epiRhandbook_jp#116]
Hi @nsbatra ,

We updated the epiRhangbook_jp to catch up to the English version and placed fully-rendered htmls into the html_outputs folder of the master branch of the epirhandbook_jp repo.

Could you update the Japanese website? Many thanks for considering my request.

**Comment by nsbatra** [comment]
@ysaito8015 well noted and thank you for the update! We will do this at soonest opportunity, hopefully later this week or next.

**Comment by nsbatra** [comment]
@ysaito8015 can you please check that the live website is updated and accurate?

**Comment by ysaito8015** [comment]
@nsbatra  I confirmed that the update is now reflected. Thank you so much!
