### ISSUE TITLE
bookdown でのビルド時エラー

### ISSUE THREAD

**Issue by ysaito8015** [appliedepi/epiRhandbook_jp#91]
bookdown でビルドしているときに、下記のエラーに遭遇します
このエラーは、すべての Rmd ファイルをビルドする際に発生し、`gis.Rmd` のみを bookdown ビルドするときは発生しません
`gis.Rmd` のみを knit する場合もこのエラーは発生しません。

----

実行コマンド

```R
bookdown::render_book(input = '.', output_format = 'bookdown::bs4_book', clean = TRUE, config_file = '_bookdown.yml')

```

```R
label: unnamed-chunk-943
Quitting from lines 20951-20955 (_main.Rmd) 
Error: A data frame is not a valid object for this function.
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Registered S3 method overwritten by 'ape':
  method   from 
  plot.mst spdep
```

もしくは

```R
label: unnamed-chunk-944
Quitting from lines 20962-20966 (_main.Rmd) 
Error in find_formula.data.frame(x, verbose = FALSE) : 
  A data frame is not a valid object for this function.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

該当 chunk
`./new_pages/gis.Rmd`

```R
# ADM3 level clean
sle_adm3 <- sle_adm3_raw %>%
  clean_names() %>% # 列名の標準化
  filter(admin2name %in% c("Western Area Urban", "Western Area Rural")) # 特定の地域を残してフィルター
```

-----
環境１
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United Kingdom.utf8
 ctype    English_United Kingdom.utf8
 tz       Asia/Tokyo
 date     2022-09-21
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   2.18 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)

環境２ -> [docker image](https://hub.docker.com/repository/docker/ysaito8015/epirhandbook_jp)
 version  R version 4.2.1 (2022-06-23)
 os       Ubuntu 20.04.5 LTS
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Etc/UTC
 date     2022-09-22
 pandoc   2.18 @ /usr/local/bin/pandoc

**Comment by ysaito8015** [comment]
Fix it with using `package_name::function` in `gis.Rmd`

**Comment by ironwest** [comment]
There is no problem in Netlify page. Merge.
