### ISSUE TITLE
Translate Header Pic

### ISSUE THREAD

**Issue by hitomik723** [appliedepi/epiRhandbook_jp#99]
Hi @nsbatra Thanks for updating the website! We've announced on Twitter that the Japanese version is now available, but I just realized that we haven't translated the title in the header picture - Could you let me know what would be the steps to translate it?
![Screenshot 2022-10-08 211723](https://user-images.githubusercontent.com/48937896/194737759-a0205ae7-36ee-47e2-b829-7080be466094.png)

**Comment by nsbatra** [comment]
Can you send me the correct text? I'll send it to Calder our artist. He can
update the image and send it back

**Comment by nsbatra** [comment]
@hitomik723 I am asking Calder to make the image with 
疫学のための R ハンドブック

Please let me know if this is incorrect

**Comment by nsbatra** [comment]
Header images sent to @hitomik723 by email. Closing.
